spring:
  application:
    name: JournalApp

  datasource:
    url: jdbc:postgresql://localhost:5432/journaldb
    username: postgres
    password: pass123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

weather:
  api:
    key: def8f576a4cf35c18ffbc86142ce7710